name: cicd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source12
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t chatbot_django_app .
      - name: Publish image to Docker Hub
        run: sudo docker push ankit974/chatbot_django_app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ankit974/chatbot_django_app:latest
      #- name: Check if Container Exists
        #run: |
          #if docker ps -a --format '{{.Names}}' | grep -q '^djangoContainer$'; then
          #  docker rm -f djangoContainer1
         # fi
      - name: Run Docker Container
        run: sudo docker run -d -p 8001:80 chatbot_django_app 

